Revert "Fix pin of pathspec in CentOS 9 Stream"
This reverts commit 2b1b5641e0fa6e58aeb58e82e50f5b5dc774aefd.

Reason for revert:
Without this gem attempts to install a newer version of puppetlabs
spec helper which requires pathspec 1.0.0. With that version of
spec helper we have seen that most of puppet jobs fail with
the error below.

```
NameError: uninitialized constant Puppet
```

Because we no longer see an issue with CentOS 9 Stream now, this
reverts the commit so that we use the same approach in zed and
older releases.

The error is not seen in stable/2023.1 and later, because of
unpinned puppet-lint, so this revert is submitted to stable/zed.
(The original change was merged during zed cycle).

Change-Id: I2bb419c83d5ba6969d262ae2966ceac822bf67fc