pin beaker to 2.x versions
Beaker 3.0.0 fails to run in Puppet Openstack CI:
LoadError: cannot load such file -- serverspec
While we're investigating it, let's pin Beaker to 2.x releases.

Change-Id: Ibe5fb922628415af6ec276cf3b7718b8457d7f1b
(cherry picked from commit 885b45652adf16465291c39c6fb58a2af663eee2)